variables:
   MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - build
  - integration-test
#  - e2e-test
#  - deploy
#  - deploy-to-test

build-job:
  stage: build
  image: openjdk:17
  script:
    - echo 'Executing build'
    - echo $SONAR_TOKEN
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_PIPELINE_ID
    - ./mvnw package

integration-test-job:
  stage: integration-test  
  script:
    - echo 'Executing integration tests'

