variables:
   MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - build
  - integration-test
  - build-image
#  - e2e-test
#  - deploy
#  - deploy-to-test

build-job:
  stage: build
  image: openjdk:17
  script:
    - echo 'Executing build'
    - echo $SONAR_TOKEN
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_PIPELINE_ID
    - ./mvnw package
  artifacts:
    paths:
      - target/*.jar

integration-test-job:
  stage: integration-test  
  script:
    - echo 'Executing integration tests'

build-image-job:
  stage: build-image
  image: docker
  script:
    - docker build -t employees-app:1.0.0-$CI_PIPELINE_ID .
