FROM openjdk:17 as builder
WORKDIR app
#COPY target/*.jar employees.jar
COPY . .
RUN ./mvnw package
RUN java -Djarmode=layertools -jar target/employees-1.0-SNAPSHOT.jar extract

FROM openjdk:17
WORKDIR app
COPY --from=builder app/dependencies/ ./
COPY --from=builder app/spring-boot-loader/ ./
COPY --from=builder app/snapshot-dependencies/ ./
COPY --from=builder app/application/ ./
ENTRYPOINT ["java", \
  "org.springframework.boot.loader.JarLauncher"]